### ISSUE TITLE
ESP32: noDAC

### ISSUE THREAD

**Issue by DaveSchwarzwald** [ferbar/btcontrol#5]
Hallo, Du hast die ESP32_MAS von JohannesMTC verbessert, bezüglich dem internen DAC.
Könntest Du mir verraten, was du am DAC angeschlossen hattest und ob das funktioniert hat?
Ich bin am testen der Audiofunktionen für die Soundausgabe von RC-Fahrzeugen und hänge da gerade fest.
Ein paar Tipps wären hilfreich. Danke schon mal für das korrigieren der ESP32_MAS!

**Comment by ferbar** [comment]
Hello, jup hat funktioniert, siehe: https://www.youtube.com/watch?v=Cuze7qoyQrU
Im original warn ein paar Bugs drinnen u.a. wegen Header der Samples ist auch an den DAC geschickt worden. Da musst du am einfachsten raw files nehmen. Ich hab noch irgendwo einen fisch drinnen, bei mir knattert der Lautsprecher leider im Sekundentakt, das hab ich noch nicht gefunden. Ansonsten funktionierts. Am DAC hängt eine PAM Platine dran. ich glaub ein pam8403 ist das.

**Comment by DaveSchwarzwald** [comment]
funktioniert bei mir jetzt auch, das Problem befand sich 50cm vor dem Monitor. Fehler die man sich durch Rumprobieren selber einbaut sind immer die schlimmsten :-) und ja, den Tick pro Sekunde habe ich auch! Da ich aber auch Motorsound abspiele, hoffe ich, dass der unter geht im Gebrummel!

**Comment by ferbar** [comment]
Solang du was abspielst wirds schon untergehen. Blöd isses wenn der motor aus is, weil auch wenn du nix abspielst isses a ned weg.
